### ISSUE TITLE
Scheduled link check failing for nesp pdf documents

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-Hive/access-hive.github.io#243]
The scheduled link check is failing on some links to pdf documents on the nespclimate site.

https://github.com/ACCESS-Hive/access-hive.github.io/actions/runs/3645370379/jobs/6155457771

<details>
  <summary>Click for details</summary>

```
2022-12-08T04:52:47.7694331Z FILE: docs/configurations/access-esm.md
2022-12-08T04:52:47.7698608Z [✖] https://nespclimate.com.au/wp-content/uploads/2020/10/Webinar-slides-Getting_started_with_ACCESS.pdf → Status: 0 Error: ETIMEDOUT
2022-12-08T04:52:47.7699277Z     at Timeout.<anonymous> (/usr/local/lib/node_modules/markdown-link-check/node_modules/request/request.js:848:19)
2022-12-08T04:52:47.7699652Z     at listOnTimeout (node:internal/timers:564:17)
2022-12-08T04:52:47.7700264Z     at process.processTimers (node:internal/timers:507:7) {
2022-12-08T04:52:47.7700584Z   code: 'ETIMEDOUT',
2022-12-08T04:52:47.7700804Z   connect: true
2022-12-08T04:52:47.7701000Z }
2022-12-08T04:52:47.7701113Z 
2022-12-08T04:52:47.7701198Z 10 links checked.
2022-12-08T04:52:47.7701326Z 
2022-12-08T04:52:47.7701409Z ERROR: 1 dead links found!
2022-12-08T04:52:47.7701913Z [✖] https://nespclimate.com.au/wp-content/uploads/2020/10/Webinar-slides-Getting_started_with_ACCESS.pdf → Status: 0
```
```
2022-12-08T04:52:47.7702366Z FILE: docs/configurations/access-cm.md
2022-12-08T04:52:47.7705388Z [✖] https://nespclimate.com.au/wp-content/uploads/2020/10/Instruction-document-Getting_started_with_ACCESS.pdf → Status: 0 Error: ETIMEDOUT
2022-12-08T04:52:47.7706026Z     at Timeout.<anonymous> (/usr/local/lib/node_modules/markdown-link-check/node_modules/request/request.js:848:19)
2022-12-08T04:52:47.7706403Z     at listOnTimeout (node:internal/timers:564:17)
2022-12-08T04:52:47.7706728Z     at process.processTimers (node:internal/timers:507:7) {
2022-12-08T04:52:47.7707029Z   code: 'ETIMEDOUT',
2022-12-08T04:52:47.7707242Z   connect: true
2022-12-08T04:52:47.7707435Z }
2022-12-08T04:52:47.7707541Z 
2022-12-08T04:52:47.7707612Z 8 links checked.
2022-12-08T04:52:47.7707737Z 
2022-12-08T04:52:47.7707834Z ERROR: 1 dead links found!
2022-12-08T04:52:47.7708349Z [✖] https://nespclimate.com.au/wp-content/uploads/2020/10/Instruction-document-Getting_started_with_ACCESS.pdf → Status: 0
```
</details>

Oddly the tests had been passing. 

It may be related to an incorrect crontab specification for the scheduled check, it was checking the links every minute every sunday! Ooops. I fixed it with [this commit](https://github.com/ACCESS-Hive/access-hive.github.io/commit/d90ff2dd12d4ade94104c5b6134cfa07abf9cffd), but maybe this is now triggering some sort of DDOS/spam protection, as the links load fine manually.

I propose to wait until next week to see if they're still failing, and then perhaps they can be added to the ignore list.

**Comment by aidanheerdegen** [comment]
Ok, passing now, will close this

https://github.com/ACCESS-Hive/access-hive.github.io/actions/runs/3667193320
